// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace my_Estore.Models
{
    public partial class Account
    {
        public Account()
        {
            Carts = new HashSet<Cart>();
        }

        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string AvatarUrl { get; set; }
        public string Role { get; set; }

        public virtual ICollection<Cart> Carts { get; set; }
    }
}