// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace my_Estore.Models
{
    public partial class Cart
    {
        public Cart()
        {
            CartItems = new HashSet<CartItem>();
        }

        public int CartId { get; set; }
        public string UserName { get; set; }
        public int Status { get; set; }

        public string RecipientName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PaymentMethod { get; set; }
        public DateTime? PurchaseDate { get; set; }

        public virtual Account UserNameNavigation { get; set; }
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}